CONFIG_ZMK_KEYBOARD_NAME="MarkovChainKeyboard"

CONFIG_ZMK_MOUSE=y
CONFIG_NFCT_PINS_AS_GPIOS=y
CONFIG_ZMK_BLE=y

CONFIG_ZMK_STUDIO=y
CONFIG_ZMK_STUDIO_LOCKING=n

CONFIG_INPUT=y
CONFIG_RGBLED_WIDGET=y
CONFIG_ZMK_USB_LOGGING=n

CONFIG_ZMK_KSCAN_DEBOUNCE_PRESS_MS=5
CONFIG_ZMK_KSCAN_DEBOUNCE_RELEASE_MS=5

# zmk stack sizes
CONFIG_ZMK_BLE_THREAD_STACK_SIZE=3072
CONFIG_ZMK_LOW_PRIORITY_THREAD_STACK_SIZE=3072
CONFIG_INPUT_THREAD_STACK_SIZE=3072
CONFIG_BT_CTLR_PHY_2M=n
